# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory/v1/inventory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inventory/v1/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cinventory/v1/inventory.proto\x12\x0cinventory.v1\"^\n\x13ReserveStockRequest\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"\xc2\x01\n\x14ReserveStockResponse\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32).inventory.v1.ReserveStockResponse.Status\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"F\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0c\n\x08RESERVED\x10\x01\x12\x16\n\x12INSUFFICIENT_STOCK\x10\x02\"W\n\x13ReleaseStockRequest\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\"(\n\x14ReleaseStockResponse\x12\x10\n\x08released\x18\x01 \x01(\x08\x32\xc0\x01\n\x10InventoryService\x12U\n\x0cReserveStock\x12!.inventory.v1.ReserveStockRequest\x1a\".inventory.v1.ReserveStockResponse\x12U\n\x0cReleaseStock\x12!.inventory.v1.ReleaseStockRequest\x1a\".inventory.v1.ReleaseStockResponseBRZPgithub.com/vladiant/choreography-saga/order/internal/pb/inventory/v1;inventoryv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory.v1.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/vladiant/choreography-saga/order/internal/pb/inventory/v1;inventoryv1'
  _globals['_RESERVESTOCKREQUEST']._serialized_start=46
  _globals['_RESERVESTOCKREQUEST']._serialized_end=140
  _globals['_RESERVESTOCKRESPONSE']._serialized_start=143
  _globals['_RESERVESTOCKRESPONSE']._serialized_end=337
  _globals['_RESERVESTOCKRESPONSE_STATUS']._serialized_start=267
  _globals['_RESERVESTOCKRESPONSE_STATUS']._serialized_end=337
  _globals['_RELEASESTOCKREQUEST']._serialized_start=339
  _globals['_RELEASESTOCKREQUEST']._serialized_end=426
  _globals['_RELEASESTOCKRESPONSE']._serialized_start=428
  _globals['_RELEASESTOCKRESPONSE']._serialized_end=468
  _globals['_INVENTORYSERVICE']._serialized_start=471
  _globals['_INVENTORYSERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
