# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from payment.pb.inventory.v1 import inventory_pb2 as inventory_dot_v1_dot_inventory__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventory/v1/inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """InventoryService is the single synchronous gRPC leg of the saga (tech-stack §6,
    C-10, FR-15, FR-16). Payment calls ReserveStock; compensation uses ReleaseStock.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveStock = channel.unary_unary(
                '/inventory.v1.InventoryService/ReserveStock',
                request_serializer=inventory_dot_v1_dot_inventory__pb2.ReserveStockRequest.SerializeToString,
                response_deserializer=inventory_dot_v1_dot_inventory__pb2.ReserveStockResponse.FromString,
                _registered_method=True)
        self.ReleaseStock = channel.unary_unary(
                '/inventory.v1.InventoryService/ReleaseStock',
                request_serializer=inventory_dot_v1_dot_inventory__pb2.ReleaseStockRequest.SerializeToString,
                response_deserializer=inventory_dot_v1_dot_inventory__pb2.ReleaseStockResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """InventoryService is the single synchronous gRPC leg of the saga (tech-stack §6,
    C-10, FR-15, FR-16). Payment calls ReserveStock; compensation uses ReleaseStock.
    """

    def ReserveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=inventory_dot_v1_dot_inventory__pb2.ReserveStockRequest.FromString,
                    response_serializer=inventory_dot_v1_dot_inventory__pb2.ReserveStockResponse.SerializeToString,
            ),
            'ReleaseStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseStock,
                    request_deserializer=inventory_dot_v1_dot_inventory__pb2.ReleaseStockRequest.FromString,
                    response_serializer=inventory_dot_v1_dot_inventory__pb2.ReleaseStockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.v1.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.v1.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """InventoryService is the single synchronous gRPC leg of the saga (tech-stack §6,
    C-10, FR-15, FR-16). Payment calls ReserveStock; compensation uses ReleaseStock.
    """

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.v1.InventoryService/ReserveStock',
            inventory_dot_v1_dot_inventory__pb2.ReserveStockRequest.SerializeToString,
            inventory_dot_v1_dot_inventory__pb2.ReserveStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.v1.InventoryService/ReleaseStock',
            inventory_dot_v1_dot_inventory__pb2.ReleaseStockRequest.SerializeToString,
            inventory_dot_v1_dot_inventory__pb2.ReleaseStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
